### ISSUE TITLE
add re-run ability to UI

### ISSUE THREAD

**Issue by Strandedpirate** [brigadecore/kashti#182]
1. As an end user I need the ability to re-run a build and/or individual jobs from the UI.
2. After navigating to the build view I should see a button/icon that allows me to re-run the entire build.
3. After navigating to the build view I should see a button/icon that allows me to re-run individual jobs from the build.
4.   Re-running individual jobs will NOT honor any parallelization originally defined in the main build script.

**Comment by krancour** [comment]
> so far we've used Brigade exclusively as read-only

s/Brigade/Kashti/

But this is a correct statement... and unfortunately Kashti 1.x needs to remain that way. Kashti doesn't authenticate users because, frankly, the Brigade APIs to support that don't exist. Without authenticating, it's not possible to determine if a user is _authorized_ to re-run a build (or individual job, which, as it's been noted it harder).

Brigade 2.0 should address most of this, if not all. It adds a robust API that includes authn and authz. It should be easy for Kashti 2.0 to authenticate users and authorize requests to re-run a worker.

This being said, re-running individual jobs remains tricky, however, Brigade 2.0 will at least _attempt_ to deliver an option that permits stateless (externalized state is ok) workflows to re-run while utilizing cached results from jobs that have already succeeded.

I'm going to label this as a 2.0 issue.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
