### ISSUE TITLE
Maintainers ability to troubleshoot using kashti without brig

### ISSUE THREAD

**Issue by carolynvs** [brigadecore/kashti#269]
This is a hard issue to articulate so I apologize up front! As I have been using brigade + Kashti for Porter's CI, sometimes we have gotten into situations where the build would fail not due to our tests failing but because of our infrastructure. Something in brigade or the underlying cluster wasn't working work properly and we couldn't tell why we suddenly couldn't merge a pull request. 

We would be blocked and have to spend some time with our CI system. 😂 

Usually we didn't have a link back to a kashti build page (which is why I opened #267). The way these problems are usually resolved is that I would ask @vdice to help. He would use brig or kubectl to diagnose the problem (Vaughn keep me honest).

One thing that has made me wary of using Brigade for my open source projects where maintainers aren't all on our team, is that process of troubleshooting isn't as equal for those maintainers who aren't on the team. They most likely won't either have access to the kuberentes cluster that brigade is running on, OR would have the same level of intimate knowledge that Vaughn has (or others on my team since we hoarde all the brigade maintainers) and know how to troubleshoot and fix the problem.

I want all of my maintainers to be able to have access to the same things as me and be able to use common, documented tools to solve problems without feeling like they are spending more time than they want on the CI system. If they could troubleshoot everything from kashti (not fix perhaps but at least identify problems, see pod logs, know something was down, etc), it would be more on the same level as what they can do with other CI providers.

So I just wanted to report what I have had trouble with myself, and see what's possible with Kashti in terms of troubleshooting brigade and its cluster?

**Comment by krancour** [comment]
@carolynvs agree on all of this...

Kashti 1.x is pretty heavily constrained by the fact that it permits anonymous access-- and only anonymous access. Without any authentication, all that can ever be shown is that which is (hopefully) suitable for public consumption. Enabling some kind of authn / authz isn't practical for 1.x because, frankly, the Brigade APIs to support it don't exist, but...

Brigade 2.0 + Kashti 2.0 should address all of your concerns. They're also planned to be (and shaping up to be) less k8s-centric-- meaning at worst, you might fall back to the `brig` CLI if Kashti isn't letting you do something you need to do. Falling back to `kubectl` for troubleshooting should happen rarely, if ever.

**Comment by krancour** [comment]
cc @ danieldelao

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
