### ISSUE TITLE
Show brigade.js at top of build metadata

### ISSUE THREAD

**Issue by technosophos** [brigadecore/kashti#33]

**Comment by krancour** [comment]
Disregard the following thought vis-a-vis 1.x.

In 2.0, this might not make sense because Brigade 2.0 doesn't assume that all workers are driven by a `brigade.js` file. i.e. The worker knows what file(s) it needs and core Brigade doesn't care.

What probably makes sense WRT 2.0 is if a build view (event/worker really, since 2.0 ditches the term "build") has a tab that can show worker details. Brigade creates these details when an event is created and they're largely created from a project-level template. This template _may_ sometimes include embedded files, such as `brigade.js`. Being able to see those would be _awesome_.

In the case where a project/event integrates with git and retrieves files like `brigade.js` (or similar) from there, link out to the repository (and correct branch, commit, etc. thereof) would be useful as well, since that would be the best way for the user to locate applicable `brigade.js` (or similar).

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
